Use standard Objects class instead of Guava (#1261)

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -20,6 +20,13 @@ jobs:
 
     steps:
       - uses: actions/checkout@master
+      - name: Check limited Guava usage
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          if grep -I -r --exclude-dir=.github "com.google.common.base.Objects" . ; then
+            echo "Error: use java.util.Objects instead of com.google.common.base.Objects"
+            exit 1
+          fi
       - name: Setup java
         uses: actions/setup-java@v1
         with:
